export interface WebsiteTopic {
  id: string;
  name: string;
  category: string;
  icon: string;
  description: string;
  suggestedPages: string[];
  keyFeatures: string[];
}

export const ASSIGNMENT_TOPIC_POOL: WebsiteTopic[] = [
  {
    id: "restaurant",
    name: "Modern Restaurant & Cafe",
    category: "Food & Dining",
    icon: "🍕",
    description: "Build an exquisite dining website with interactive menus, online table reservation, chef highlights, and customer reviews.",
    suggestedPages: ["Home", "Menu", "About Us", "Reservations", "Contact"],
    keyFeatures: ["Filterable food categories", "Table booking form", "Dish pricing cards", "Chef showcase", "Google Maps location"],
  },
  {
    id: "hotel",
    name: "Luxury Boutique Hotel & Resort",
    category: "Hospitality",
    icon: "🏨",
    description: "Design a luxury resort website showcasing premium suites, virtual room amenities, booking inquiry, and guest experience stories.",
    suggestedPages: ["Home", "Rooms & Suites", "Amenities", "Dining & Spa", "Contact & Booking"],
    keyFeatures: ["Room filter by price/type", "Amenities grid with icons", "Photo gallery lightbox", "Stay inquiry form", "Customer testimonials"],
  },
  {
    id: "real-estate",
    name: "Prime Real Estate & Property Hub",
    category: "Real Estate",
    icon: "🏢",
    description: "Create a modern real estate agency website featuring featured property listings, neighborhood guides, mortgage calculators, and agent contacts.",
    suggestedPages: ["Home", "Properties", "Featured Listings", "Agents", "Contact"],
    keyFeatures: ["Property search filters", "Card layout with beds/baths badges", "Agent contact cards", "Virtual tour request form", "Interactive map"],
  },
  {
    id: "gym-fitness",
    name: "PowerPulse Gym & Fitness Club",
    category: "Health & Fitness",
    icon: "🏋️",
    description: "Develop an energetic fitness club website with workout programs, trainer profiles, BMI calculator, membership tiers, and free trial pass.",
    suggestedPages: ["Home", "Classes & Schedule", "Trainers", "Pricing Plans", "Join Now"],
    keyFeatures: ["Weekly class schedule timetable", "Membership pricing cards", "Interactive BMI calculator", "Trainer bio cards", "Free pass signup form"],
  },
  {
    id: "coffee-shop",
    name: "Artisanal Coffee & Roastery",
    category: "Food & Beverage",
    icon: "☕",
    description: "Design a warm, cozy cafe website featuring handcrafted coffee blends, brewing guides, loyalty club, and online pickup ordering.",
    suggestedPages: ["Home", "Coffee Menu", "Our Story & Roasting", "Locations", "Order Online"],
    keyFeatures: ["Illustrated drink menu", "Coffee origin stories", "Order for pickup form", "Customer rewards banner", "Opening hours badge"],
  },
  {
    id: "ecommerce",
    name: "UrbanTrend E-commerce Store",
    category: "Retail & Shopping",
    icon: "🛍️",
    description: "Build a responsive online shop showcase with product catalogs, dynamic filter sidebar, cart drawer preview, and featured promotions.",
    suggestedPages: ["Home", "Shop / Catalog", "Product Detail", "Special Deals", "Cart / Checkout"],
    keyFeatures: ["Product grid with hover effects", "Category filter sidebar", "Sale discount tags", "Newsletter signup", "Cart counter badge"],
  },
  {
    id: "travel-agency",
    name: "Wanderlust Travel & Tour Agency",
    category: "Tourism",
    icon: "✈️",
    description: "Create an inspiring tour booking portal highlighting exotic destinations, holiday packages, travel guides, and visa advisory.",
    suggestedPages: ["Home", "Tour Packages", "Destinations", "Travel Guides", "Book a Trip"],
    keyFeatures: ["Destination photo cards", "Package pricing & duration badges", "Trip inquiry form", "Customer travel reviews", "Interactive world map section"],
  },
  {
    id: "photography",
    name: "Lumina Creative Photography Studio",
    category: "Creative Arts",
    icon: "📷",
    description: "Showcase high-resolution photography portfolios with categorized galleries, client testimonials, booking scheduler, and pricing packages.",
    suggestedPages: ["Home", "Portfolio Gallery", "Services", "About the Artist", "Book Session"],
    keyFeatures: ["Masonry grid photo gallery", "Category filter (Weddings, Portraits, Wildlife)", "Lightbox preview modal", "Session booking form", "Client review carousel"],
  },
  {
    id: "medical-clinic",
    name: "CarePoint Healthcare & Medical Clinic",
    category: "Healthcare",
    icon: "🏥",
    description: "Develop a clean, trustworthy medical clinic website with department details, doctor bios, appointment scheduling, and emergency contacts.",
    suggestedPages: ["Home", "Specialties & Doctors", "Services", "Patient Info", "Book Appointment"],
    keyFeatures: ["Doctor appointment booking form", "Department icon grid", "Emergency hotline banner", "Health tips blog section", "Patient FAQs"],
  },
  {
    id: "school-academy",
    name: "Apex International School & Academy",
    category: "Education",
    icon: "🎓",
    description: "Build an engaging educational institution portal featuring academic programs, faculty directory, admissions portal, and campus life.",
    suggestedPages: ["Home", "Academics & Courses", "Admissions", "Faculty", "Campus Life & Contact"],
    keyFeatures: ["Course overview cards", "Online admission form", "Upcoming events calendar", "Faculty directory with qualifications", "Virtual campus tour section"],
  },
  {
    id: "event-management",
    name: "GrandCelebrations Event & Wedding Planner",
    category: "Events & Entertainment",
    icon: "🎯",
    description: "Design an elegant event planning website showcasing corporate galas, dream weddings, stage decorations, and custom budget estimators.",
    suggestedPages: ["Home", "Event Services", "Past Events Gallery", "Pricing Packages", "Get a Quote"],
    keyFeatures: ["Event type selector (Weddings, Birthdays, Corporate)", "Decoration photo gallery", "Budget estimation inquiry form", "Client success stories", "Vendor partner logos"],
  },
  {
    id: "car-rental",
    name: "DriveEase Luxury & Economy Car Rental",
    category: "Automotive & Transport",
    icon: "🚗",
    description: "Create an intuitive vehicle rental platform with vehicle fleet browsing, reservation dates picker, pricing calculators, and pickup locations.",
    suggestedPages: ["Home", "Fleet / Vehicles", "Rental Rates", "Locations", "Reserve Now"],
    keyFeatures: ["Vehicle filter (SUV, Sedan, Luxury, Electric)", "Specs comparison (Transmission, Fuel, Seats)", "Date & time reservation widget", "Driver terms checklist", "Customer reviews"],
  },
  {
    id: "digital-agency",
    name: "NexGen Digital & Marketing Agency",
    category: "Tech & Services",
    icon: "🚀",
    description: "Build a sleek, high-converting digital agency website highlighting SEO, web development, growth hacking, client case studies, and audit requests.",
    suggestedPages: ["Home", "Services", "Case Studies", "About Us", "Start Project"],
    keyFeatures: ["Interactive services grid", "Client case study metrics", "Free website audit request form", "Client logo ticker", "Animated statistics counters"],
  },
  {
    id: "clothing-brand",
    name: "VogueAura Fashion & Apparel Brand",
    category: "Fashion & Lifestyle",
    icon: "👗",
    description: "Design a trendsetting apparel brand website featuring lookbooks, seasonal collections, size charts, and sustainable fabric stories.",
    suggestedPages: ["Home", "Collections", "Lookbook", "Our Craft", "Contact"],
    keyFeatures: ["Collection hero banner with video/animation", "Interactive lookbook gallery", "Size guide modal", "Sustainability pledge section", "Store locator"],
  },
  {
    id: "interior-design",
    name: "Habitat Studio Interior Design & Architecture",
    category: "Architecture & Home",
    icon: "🛋️",
    description: "Develop an architectural interior design portal highlighting residential & commercial transformations, before/after comparisons, and design consultations.",
    suggestedPages: ["Home", "Projects Portfolio", "Design Services", "Our Process", "Consultation"],
    keyFeatures: ["Before & After project comparison slider", "Design style quiz / style cards", "Project case studies with material breakdown", "Consultation booking form", "Press & awards section"],
  },
  {
    id: "construction-company",
    name: "SolidGround Infrastructure & Construction",
    category: "Industrial & Construction",
    icon: "🏗️",
    description: "Create a heavy-duty construction company website showcasing ongoing civil engineering projects, safety certifications, machinery fleet, and bidding.",
    suggestedPages: ["Home", "Projects", "Capabilities & Safety", "Machinery Fleet", "Request a Bid"],
    keyFeatures: ["Project timeline & milestone cards", "Safety metrics badge counter", "Bid / Quote submission form", "Equipment catalogue", "Accreditation certificates"],
  },
  {
    id: "tech-startup",
    name: "CloudScale SaaS & Tech Startup",
    category: "Technology",
    icon: "💡",
    description: "Build an ultra-modern SaaS landing page with interactive product tour, feature breakdown, live API demo widget, and tiered pricing plans.",
    suggestedPages: ["Home", "Features", "Pricing", "Documentation / API", "Book a Demo"],
    keyFeatures: ["Animated product preview mockup", "Feature comparison matrix", "Monthly / Annual pricing switcher", "Interactive demo request modal", "Security & compliance badges"],
  },
  {
    id: "ngo",
    name: "HopeHarbor Global Charity & NGO",
    category: "Community & Non-Profit",
    icon: "🤝",
    description: "Design a heartfelt non-profit foundation website highlighting humanitarian causes, transparency reports, donation calculator, and volunteer signups.",
    suggestedPages: ["Home", "Our Causes", "Impact Reports", "Volunteer", "Donate Now"],
    keyFeatures: ["Cause progress bar with donation goals", "Custom donation amount selector", "Volunteer registration form", "Transparent annual financial graphs", "Beneficiary video stories"],
  },
  {
    id: "food-delivery",
    name: "QuickBite Express Food Delivery",
    category: "Food Logistics",
    icon: "🍔",
    description: "Build a vibrant on-demand food delivery website featuring local restaurant listings, track delivery widget, trending meal deals, and rider signups.",
    suggestedPages: ["Home", "Browse Food", "Deals & Combos", "Become a Rider", "Track Order"],
    keyFeatures: ["City/Area delivery search bar", "Meal combo cards with discount badges", "Rider application form", "Live order progress stepper", "App download promotional section"],
  },
  {
    id: "hair-salon",
    name: "VelvetGlow Hair Salon & Spa",
    category: "Beauty & Wellness",
    icon: "✂️",
    description: "Create a chic beauty salon and spa portal with hairstyle lookbooks, treatment pricing menus, stylist bios, and instant appointment booking.",
    suggestedPages: ["Home", "Treatments & Hair", "Stylists", "Price List", "Book Appointment"],
    keyFeatures: ["Styling portfolio cards", "Treatment duration & pricing table", "Stylist selection dropdown in booking form", "Gift voucher purchase section", "Client before/after showcase"],
  },
  {
    id: "pet-care",
    name: "HappyPaws Pet Care & Veterinary Clinic",
    category: "Pet & Animals",
    icon: "🐾",
    description: "Develop a friendly pet hotel, grooming, and veterinary clinic portal with pet adoption profiles, vaccination schedules, and grooming packages.",
    suggestedPages: ["Home", "Veterinary & Grooming", "Pet Adoption", "Boarding Services", "Contact"],
    keyFeatures: ["Pet adoption gallery with breed/age tags", "Grooming package comparison", "Vet appointment scheduler", "Emergency pet care instructions", "Pet parent testimonials"],
  },
  {
    id: "yoga-wellness",
    name: "SereneMind Yoga & Wellness Sanctuary",
    category: "Wellness & Mindfulness",
    icon: "🧘",
    description: "Design a tranquil meditation and yoga studio website with class schedules, meditation sound previews, retreat registrations, and instructor bios.",
    suggestedPages: ["Home", "Yoga Classes", "Workshops & Retreats", "Instructors", "Join Sanctuary"],
    keyFeatures: ["Interactive class schedule filter", "Mindfulness audio snippet player", "Retreat booking form with countdown", "Instructor specialization badges", "Pricing tiers"],
  },
  {
    id: "auto-repair",
    name: "PrecisionDrive Auto Repair & Detailing",
    category: "Automotive Services",
    icon: "🔧",
    description: "Build a trusted auto repair workshop portal featuring diagnostic service lists, instant repair estimates, tire/battery store, and emergency road assistance.",
    suggestedPages: ["Home", "Repair Services", "Auto Detailing", "Free Estimate", "Emergency Help"],
    keyFeatures: ["Service diagnostic checklist", "Instant repair quote request form", "Emergency roadside call button", "Warranty assurance badges", "Customer satisfaction ratings"],
  },
  {
    id: "yacht-cruise",
    name: "OceanicVenture Yacht & Cruise Charters",
    category: "Luxury Travel",
    icon: "⛵",
    description: "Create an ultra-luxury private yacht charter website highlighting coastal itineraries, vessel specifications, onboard chef dining, and VIP charters.",
    suggestedPages: ["Home", "Yacht Fleet", "Cruising Routes", "Private Events", "Charter Inquiry"],
    keyFeatures: ["Fleet specification filters (Length, Capacity, Speed)", "Itinerary map overview", "Charter inquiry form", "Onboard luxury photo galleries", "Captain & crew profiles"],
  },
  {
    id: "law-firm",
    name: "JusticeFirst Legal Advocates & Law Firm",
    category: "Legal & Professional",
    icon: "⚖️",
    description: "Develop an authoritative legal services portal featuring practice areas, attorney profiles, free confidential consultation requests, and legal guides.",
    suggestedPages: ["Home", "Practice Areas", "Our Attorneys", "Case Results", "Free Consultation"],
    keyFeatures: ["Practice area directory with icons", "Confidential case evaluation form", "Attorney credentials and bar admissions", "Settlement track record metrics", "Legal FAQs"],
  },
];

export const PROJECT_TECHNICAL_REQUIREMENTS = [
  { id: "html5", title: "HTML5 Semantic Structure", description: "Use semantic tags (<header>, <nav>, <main>, <section>, <article>, <aside>, <footer>) with clean indentation." },
  { id: "css3", title: "Modern CSS3 Styling", description: "Use custom CSS variables, Flexbox, CSS Grid, polished typography, and aesthetic color palettes." },
  { id: "bootstrap", title: "Bootstrap or Responsive Grid", description: "Implement responsive layouts using Bootstrap components or clean mobile-first grid systems." },
  { id: "js", title: "JavaScript Interactivity", description: "Interactive components like mobile menu toggle, tabs, modal popups, filters, or form validations." },
  { id: "responsive", title: "100% Fully Responsive Design", description: "Flawless rendering on Mobile (320px+), Tablet (768px+), Laptop (1024px+), and Desktop screens." },
  { id: "animations", title: "CSS Animations & Transitions", description: "Smooth button hover effects, subtle fade-in reveals, smooth scrolling, and micro-interactions." },
  { id: "loader", title: "Loading Screen / Page Loader", description: "Professional preloader animation that disappears smoothly once the webpage assets are ready." },
  { id: "sections", title: "Multiple Sections / Structured Pages", description: "Hero banner, feature cards, about section, gallery/menu, testimonials, contact form, and footer." },
  { id: "ui_ux", title: "Professional UI/UX Quality", description: "Harmonious color contrast, modern Google Fonts, crisp imagery (Unsplash/Pexels), and intuitive navigation." },
  { id: "clean_code", title: "Clean Folder Structure", description: "Organized directories (e.g. index.html, /css/style.css, /js/main.js, /assets/images)." },
  { id: "git_github", title: "Git & GitHub Version Control", description: "Published on a public GitHub repository with clear commit messages and README.md." },
  { id: "live_deploy", title: "Live Website Deployment", description: "Deployed live on Vercel, Netlify, or GitHub Pages with HTTPS." },
  { id: "portfolio", title: "Mandatory Personal Portfolio Website", description: "Must include a link to your personal developer portfolio showcasing this project and your skill set." },
];

export const DEFAULT_WEB_DEV_ASSIGNMENT_TITLE = "Web Development Module 1 Final Project: Responsive Website & Portfolio";
export const DEFAULT_WEB_DEV_ASSIGNMENT_DESCRIPTION = 
  "Welcome to your Module 1 (HTML & CSS) Capstone Assignment! You have been automatically assigned a unique website project topic. You must design and develop a fully responsive, multi-section website from scratch using HTML5, CSS3, Bootstrap/Grid, and JavaScript. You must also build/link your Personal Developer Portfolio website.";
